---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-creds
  namespace: default
spec:
  encryptedData:
    password: AgBWja6c/iImzdc7ycCCyFao5I2FVd5u8+VrIfRvXOPWwFq6/PL7utgHEldotYy3+qUYtQRIi1wDylIp8QLXnc8pfKvjMpp8EumL51mQxFvZDyg7Ml0Q+zz6+FIx9XT0WMD75nbf2HWFvY2Mh7Bef5TnrzX6M74sOS/UKY5zvayk3MVFXt5BpW/X5A6TwPN5sF+MZuLwBcVETVZ+a4JDL358dc07ag6RvZxATN4xIvH4TSLqd+uk0IAYURWxieyB6Z3ZzmYp/0cjIUq+6n4a+uC49RDrJNHNfWcLtpOHqD+20I4/kt4pIe/TLMwfOsiz3i9u4BLGmmbKjzxYJVyRyvIxkZtBfdzEIwhb9YD1xeB0flCVaKkW039kRgPdGkSMMl5OI0TQ1xyYAv+pGsmoxlYVPobOd2bhQwpZSVGq4hFPNvRDujzoIrmmr6MhlUJETxe0xiaX8uFsgUNWT9ITz2nHexRxNYOq4yXpK3z8kY3spbJxYUBIMntmDDwnlpKySnKi4x6rHejL7tfDlI/NO71+khUnj8VQB6GS7v5G9DA4xXfZ6KfIBn1byTcDPd3X0crIBczWrmpRSIWzFhxZCJPfQ6jY2DBhruZtnIg3JCgGo/Q3e5LCnL/gMw5n5pmxq+JoBUCOZ1c/vFX8c4L8zA5hqCwhK//ygGGbxlPw8WAS7ufGQA2xFh8n2GcpPtGzw2M2rkWdFN2fIUj0BQ==
    username: AgAtQ1RS8QB9LSz9oVXI5GIdooCMP5AnyP0cj32wfPAXfdZF4H1tsJieoBhMmRofIx5W5pcM9TU0ucxBrQhljGUkQ0LkHerT98lNfERpJyFvSunTVN6zYpa5TPgUFlaoBdO7+jzNLwMhJxCfx838GXih4KWcQqAIgmoAHz1gM3JPTpKJ95qkFu+l3gEoqtKH0HN8FH61hcEkb0kq944wpit+s01RtPQRwBheTvi7Tc73vrpi2SpkQe9QnO3mn/S7qrE/v0aCnE5P75d6ikbtnoZ36XGD7txNqbmo8fbEYqH/VRO8UXnemTxCHP2jAqyls67rMdiqz2L+oMbSaHeon1REMamUPDQTcINTnZ1etW8uoI0ToSSZ3lAaHW2J2+4SakcSGPZGXf/4v8uigAabe/PBsEJ2a4yDo3+Yv1De2H5gd9TcpbPdvLqeGbXDPO/1xyTKlHIr9x0sB4Vtm1DylpeBZ8BEEx2eUVPJpANzzNL8sAqSW4e02ZMttpkoR1tDzTbz08BkT0nhwKu2mh4zQ4nvbqclJQD/S67u9mMGQGlPRig197JE4+5hkHr/bBiHfTPRkrUneESFc2nDJXjA3soRApJh26xTtQgOMKLv8/QcXqn8Dx4eHSKnuSkFP2B22iSKEjzvi3Zd/NOoztzod4VV2VUcrcJKflEShlYnJoJMj8EPJ+2GKv8eWMi9dCqmXlGo0fxkhA==
  template:
    metadata:
      name: db-creds
      namespace: default
